### ISSUE TITLE
ID of public key returned by create needs to be prefixed by the created DID

### ISSUE THREAD

**Issue by codeglobally** [decentralized-identity/sidetree-core#104]
{
    "context": "https://w3id.org/did/v1",
    "id": "did:sidetree:EiD3j1DfUzypfK8ZP",
    "publicKey": [
        {
            "type": "RsaVerificationKey2018",
            "id": "did:sidetree:EiD3j1DfUzypfK8ZP#master",
            "publicKeyPem": "-----BEGIN PUBLIC KEY----- -----END PUBLIC KEY-----\n"
        }
    ]
}

**Comment by thehenrytsai** [comment]
Implement according to:

https://github.com/w3c-ccg/did-spec/issues/97#issuecomment-457848099

**Comment by thehenrytsai** [comment]
Will require all public key IDs to be fragments (starts with #).

**Comment by thehenrytsai** [comment]
The following addressed this issue:
1. Protocol and code change to require fragment based key id (prefixed with `#`): https://github.com/decentralized-identity/sidetree-core/commit/db3d83c8bd959cf11d0fddd2ecf7862c31734b3a
1. https://github.com/decentralized-identity/sidetree-core/pull/123/commits/613c0807a7571d15e21cdfd9be6dd659ee00acc9
