### ISSUE TITLE
anchorFileJson contains unencoded buffer

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree-core#106]
```
{"batchFileHash":"EiBz-l5-pd0K9ZipVI_GMBaXmY1r9BCVNM5z18Sl7Jyx7Q","merkleRoot":{"type":"Buffer","data":[55,11,216,118,62,67,205,215,207,35,44,11,221,166,254,81,225,55,96,166,78,121,190,167,195,37,87,154,145,186,102,62]}}
```

merkleRoot should be string encoded as hex or base64.

**Comment by thehenrytsai** [comment]
Thanks @OR13 for finding the bug, fix checked in in https://github.com/decentralized-identity/sidetree-core/commit/60bf7ab1b201e1597b21eb95f3fbf83ac83dc14f.

Note: used base64url encoding scheme just like rest of the system.
