### ISSUE TITLE
Ensure that the Sidetree node's IPFS component is setup to only replicate/store Sidetree data

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree-core#109]
Most IPFS installs allow the IPFS instance to replicate and store random data from around the network. This is something we need to block in our use. The Sidetree node should only be coded to replicate and store Sidetree-specific data.

**Comment by thehenrytsai** [comment]
Opened this issue in sidetree-ipfs: https://github.com/decentralized-identity/sidetree-ipfs/issues/30
