### ISSUE TITLE
Change request format to use JWS scheme

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree-core#122]

**Comment by thehenrytsai** [comment]
1. Protocol update: https://github.com/decentralized-identity/sidetree-core/commit/d35e774ce3d86bec4294fc1fce87fc725e0d68f3
1. Implementation: https://github.com/decentralized-identity/sidetree-core/commit/d68372e9b66744309cf362c2fe5942dce09737af
1. Signature signing and verification update: https://github.com/decentralized-identity/sidetree-core/commit/1a931e8a65e6042767a9a8ce11350bd7b8ea9df4

**Comment by logangirvin** [comment]
"alg" is a [required header parameter](https://tools.ietf.org/html/rfc7515#section-4.1.1) for JWS to distinguish signing algorithm used, however is [not used or required](https://github.com/decentralized-identity/sidetree-core/blob/master/docs/protocol.md#did-and-did-document-creation) for signed operation requests.

**Comment by thehenrytsai** [comment]
`alg` added as required property in https://github.com/decentralized-identity/sidetree-core/commit/e50e2271bed2285c7d2d17f13a89c748a6629878
