### ISSUE TITLE
Update the Rooter Pseudo Code in Implementation Doc

### ISSUE THREAD

**Issue by sylar217** [decentralized-identity/sidetree-core#23]
Update the pseudo code of Rooter, in the implementation.md file according to the implemented version

**Comment by thehenrytsai** [comment]
Committed https://github.com/decentralized-identity/sidetree-core/commit/a80b3cf9b5dd45bc3466a37fac55e709cc76a974 and https://github.com/decentralized-identity/sidetree-core/commit/4cbcc8bc1999e89dc22251c8b65ed37634a14926 to describe the rule processing.
