### ISSUE TITLE
Content of anchorFile differs from protocol spec

### ISSUE THREAD

**Issue by ebaizel** [decentralized-identity/sidetree-core#36]
It looks like the sidetree-core implementation constructs the anchor file with the `batchFileAddress` whereas the sidetree protocol mentions it being the `batchFileHash`:

https://github.com/decentralized-identity/sidetree-core/blob/bc48eecb9d15637e5b14f7c938e77e3bdb5fb7ba/src/Rooter.ts#L79

It seems like the CAS address would be more helpful since we can also use that to verify its existence

**Comment by thehenrytsai** [comment]
Thanks @ebaizel, I will fix it in the up-coming pull request which should be out today or tomorrow.

**Comment by ebaizel** [comment]
thanks Henry, so will the anchorFile contain the `batchFileAddress` or the `batchFileHash`?

**Comment by thehenrytsai** [comment]
They mean the same thing but I am leaning towards `batchFileHash`.

**Comment by thehenrytsai** [comment]
Fix https://github.com/decentralized-identity/sidetree-core/commit/ffcdc4b92d0006448ff19a88382856cebfaacac9 merged into master.

Feel free to reopen if needed.
