### ISSUE TITLE
Transaction Pagination on the Blockchain Sidetree

### ISSUE THREAD

**Issue by ebaizel** [decentralized-identity/sidetree-core#37]
This is a question around pagination of the `GET /v1.0/transactions` endpoint.

https://github.com/decentralized-identity/sidetree-core/blob/master/docs/implementation.md#request-example

The sidetree protocol includes a `afterBlockNumber` field for paginating through GET transactions requests.  This is specific to Bitcoin as the Ethereum Sidetree will be using other methods for specifying pagination location.

Could we rename that field to a more generic name?  Fwiw, on Ethereum the anchor file hashes will all be saved in one smart contract and stored within an array.  So the pagination value would point to an index within that array.

**Comment by thehenrytsai** [comment]
Agree on making interface more generic. That specific API has already been reworked yesterday and the next pull request (coming out today/tomorrow) will look more generic, you can see the updated spec [here](https://github.com/decentralized-identity/sidetree-core/blob/henrytsai/main/docs/implementation.md) if you cannot wait.

The essence of the change is that the API now will look like:

`GET /<api-version>/transactions?after=<transaction-number>`

**Comment by thehenrytsai** [comment]
Commit https://github.com/decentralized-identity/sidetree-core/commit/0098a9458042ec41ce011dbab0b52f9782e44cb8 merged into master.

Closing this question, feel free to reopen if needed.
