### ISSUE TITLE
Change DID Document Service Endpoint descriptors to match Identity Hub spec

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree-core#6]
Here is what the Service Endpoint descriptors should look like, per the Identity Hub spec: https://github.com/decentralized-identity/identity-hub/blob/master/explainer.md#did-document-service-endpoint-descriptors

**Comment by thehenrytsai** [comment]
Thanks Daniel for fixing. [Pull request](https://github.com/decentralized-identity/sidetree-core/commit/d6b18e66e64ca0058e4eca86b0b8068235510aae)
